---
# tasks file for ansible-role-pdsh-machines
#

 - include: redhat.yml
   when: ansible_os_family == "RedHat"

 - name: populate machines file locally
   lineinfile:
         dest={{ pdsh_local_file }}
         regexp='^{{ hostvars[item].inventory_hostname }}$'
         line="{{ hostvars[item].inventory_hostname }}" 
         state=present
         create=yes
   with_items: "{{ pdsh_group }}"
   delegate_to: localhost 
   sudo: no
   register: reg_pdsh_machines

 - name: copy in /etc/machines
   copy: src={{ pdsh_local_file }} dest=/etc/machines mode=0644

# TODO: Make dsh groups
# - debug: var=groups
#
# - name: populate dsh group files locally
#   lineinfile:
#         dest=files/dsh/group/{{ item[0].key }}
#         regexp='^{{ inventory_hostname }}$'
#         line='{{ inventory_hostname }}'
#         state=present
#         create=yes
#   with_subelements: 
#    - "{{ groups }}"
#    - "{{ groups.item[0] }}"
#   delegate_to: localhost 
#   sudo: no
