---
# tasks file for ansible-role-pdsh-machines
#

 - include: redhat.yml
   when: ansible_os_family == "RedHat"

 - name: populate machines file
   template: src='pdsh_machines.j2' dest='/etc/machines' mode='0644' owner=root group=root

# TODO: Make dsh groups
# - debug: var=groups
#
# - name: populate dsh group files locally
#   lineinfile:
#         dest='files/dsh/group/{{ item.key }}'
#         regexp='^{{ inventory_hostname }}$'
#         line='{{ inventory_hostname }}'
#         state=present
#         create=yes
#   with_dict: groups
#   delegate_to: localhost
#   become: no
